project_id = "otdyhyzghaohnhtwzkvu"

[functions.edu-availability]
verify_jwt = false

[functions.edu-create-package]
verify_jwt = false

[functions.edu-checkout-status]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.edu-charge-second-payment]
verify_jwt = false
